### ISSUE TITLE
请问这个游戏规则是什么样的？我不太会玩。。。谢谢

### ISSUE THREAD

**Issue by coding-12** [dawnchan030920/Firgency#3]

**Comment by dawnchan030920** [comment]
你好~
游戏规则可以看这个项目的网址：
dawnchan030920.github.io/Firgency
总的来说就是一个战棋游戏，左侧可以抽取，点击棋盘上的棋子可以选中（但是不会提示），点击其它地方可以进行行动（攻击、移动等）
Feel free to comment!

**Comment by coding-12** [comment]
wow~竟然收到reply了！！！谢谢【亲亲】
我去试试^_^


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawnchan030920/Firgency"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月7日(星期天) 下午2:34
收件人:&nbsp;"dawnchan030920/Firgency"<Firgency@noreply.github.com&gt;;
抄送:&nbsp;"朝气"<1565884158@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dawnchan030920/Firgency] 请问这个游戏规则是什么样的？我不太会玩。。。谢谢 (#3)





 
你好~
 游戏规则可以看这个项目的网址：
 dawnchan030920.github.io/Firgency
 总的来说就是一个战棋游戏，左侧可以抽取，点击棋盘上的棋子可以选中（但是不会提示），点击其它地方可以进行行动（攻击、移动等）
 Feel free to comment!

**Comment by dawnchan030920** [comment]
后续有问题也可以开issue鸭~
感谢您的使用！
